# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairChosen', models.CharField(choices=[('ETHUSDT', 'USDT_ETH'), ('others', 'Others')], default='ETHUSDT', max_length=1024)),
                ('periodChosen', models.CharField(choices=[('KLINE_INTERVAL_4HOUR', '4h'), ('others', 'Others')], default='KLINE_INTERVAL_4HOUR', max_length=1024)),
                ('strategy_type', models.CharField(choices=[('moving_averages', 'Moving Averages'), ('bollinger_bands', 'Bollinger Bands')], default='moving_averages', max_length=1024)),
                ('strategy_details', models.CharField(max_length=1024)),
            ],
        ),
    ]
